// Helpers for the "derived" env vars and the sourceable export file Dash
// generates per worktree. Pure functions — no fs, no DB — so they're trivially
// testable and shared by both consumers of the result (the PTY env and the
// on-disk export file), guaranteeing the two stay identical.

const TEMPLATE_REF_PATTERN = /\$\{([^}]*)\}/g;

/**
 * Evaluate `derived` templates against the worktree's allocated port values.
 * Each `${VAR}` is replaced with the resolved port. References are validated at
 * parse time (see WorkspacePortsService), so by here every `${VAR}` is known;
 * an unknown ref is left literal rather than silently blanked, so a mistake is
 * visible instead of producing `http://localhost:`.
 */
export function resolveDerivedEnv(
  templates: Record<string, string>,
  portValues: Record<string, number>,
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, template] of Object.entries(templates)) {
    out[key] = template.replace(TEMPLATE_REF_PATTERN, (whole, ref: string) => {
      const v = portValues[ref];
      return v === undefined ? whole : String(v);
    });
  }
  return out;
}

/**
 * Compose a worktree's full ordered env from its allocated Tier-2 ports and
 * `derived` templates: port vars first (declaration order), then the resolved
 * derived vars. Returns `[name, value]` string pairs — the single shape both
 * the PTY env (via Object.fromEntries) and the export file (via formatEnvExport)
 * are built from, so the two can't drift.
 */
export function composeWorktreeEnv(
  portEntries: Array<[string, number]>,
  derived?: Record<string, string>,
): Array<[string, string]> {
  const portValues: Record<string, number> = {};
  for (const [name, port] of portEntries) portValues[name] = port;

  const entries: Array<[string, string]> = portEntries.map(([name, port]) => [name, String(port)]);
  if (derived) {
    for (const [name, value] of Object.entries(resolveDerivedEnv(derived, portValues))) {
      entries.push([name, value]);
    }
  }
  return entries;
}

/** Single-quote a value for safe `source`-ing in POSIX shells. */
function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Render an ordered list of `[name, value]` env entries as a sourceable file:
 * `export NAME='value'` lines (also consumed cleanly by python-dotenv, which
 * strips the `export ` prefix). Order is the caller's — keep it stable
 * (declaration order) for clean diffs.
 */
export function formatEnvExport(entries: Array<[string, string | number]>): string {
  const header = [
    '# Generated by Dash — do not edit or commit.',
    '# Per-worktree ports + derived vars. Source it where Dash is not the launcher:',
    '#   source .env.worktree && pytest',
    '',
  ];
  const lines = entries.map(([name, value]) => `export ${name}=${shellQuote(String(value))}`);
  return [...header, ...lines, ''].join('\n');
}
