import type { WorkspacePorts } from './WorkspacePortsService';

const DEFAULT_SLOTS = 50;
const DEFAULT_STRIDE = 100;

/**
 * djb2 hash mod slots, multiplied by stride. Same worktree name → same
 * offset across machines and Dash restarts, which is the whole point of the
 * deterministic strategy: developers can share screenshots/logs without
 * "what port is the frontend on for you?" friction.
 */
export function hashOffset(name: string, slots: number, stride: number): number {
  let h = 5381;
  for (let i = 0; i < name.length; i++) {
    h = (h << 5) + h + name.charCodeAt(i);
    h = h | 0; // keep within 32-bit signed range
  }
  return (Math.abs(h) % slots) * stride;
}

/** Where a host port ultimately came from. Surfaced in tooltips. */
export type PortSource = 'fixed' | 'hash' | 'override' | 'probe';

export interface PortAssignment {
  label: string;
  hostPort: number;
  source: PortSource;
  /** Tier 2 only — the env var to inject. */
  envVar?: string;
  /** Tier 2 only — the defaultPort the assignment was derived from. */
  defaultPort?: number;
}

export interface AllocatePortsArgs {
  ports: WorkspacePorts;
  worktreeName: string;
  overrides: Record<string, number>;
  /**
   * Host ports already in use by other live workspaces. The allocator skips
   * past any of these by adding successive `stride`s to the candidate.
   */
  taken: Set<number>;
}

const PORTS_ENV_HEADER = '# Generated by Dash — do not edit';

/**
 * Render the `KEY=VALUE` lines for `.dash/ports.env`. Includes a marker
 * comment so users (and the agent) recognise the file as Dash-managed.
 * Only Tier 2 assignments contribute — fixed entries have no env var.
 */
export function renderPortsEnv(assignments: PortAssignment[]): string {
  const lines: string[] = [PORTS_ENV_HEADER];
  for (const a of assignments) {
    if (a.envVar) lines.push(`${a.envVar}=${a.hostPort}`);
  }
  return lines.join('\n') + '\n';
}

export function allocatePorts(args: AllocatePortsArgs): PortAssignment[] {
  const slots = args.ports.slots ?? DEFAULT_SLOTS;
  const stride = args.ports.stride ?? DEFAULT_STRIDE;
  const offset = hashOffset(args.worktreeName, slots, stride);

  const assignments: PortAssignment[] = [];

  for (const entry of args.ports.ports) {
    if ('port' in entry) {
      assignments.push({ label: entry.label, hostPort: entry.port, source: 'fixed' });
      continue;
    }

    const override = args.overrides[entry.envVar];
    if (override !== undefined) {
      assignments.push({
        label: entry.label,
        envVar: entry.envVar,
        defaultPort: entry.defaultPort,
        hostPort: override,
        source: 'override',
      });
      continue;
    }

    let candidate = entry.defaultPort + offset;
    let source: PortSource = 'hash';
    while (args.taken.has(candidate)) {
      candidate += stride;
      source = 'probe';
    }
    assignments.push({
      label: entry.label,
      envVar: entry.envVar,
      defaultPort: entry.defaultPort,
      hostPort: candidate,
      source,
    });
  }

  return assignments;
}
