import { describe, it, expect } from 'vitest';
import { resolveDerivedEnv, formatEnvExport, composeWorktreeEnv } from '../derivedEnv';

describe('resolveDerivedEnv', () => {
  it('substitutes a single ${VAR} reference', () => {
    expect(
      resolveDerivedEnv(
        { VITE_API_URL: 'http://localhost:${BACKEND_PORT}' },
        { BACKEND_PORT: 9200 },
      ),
    ).toEqual({ VITE_API_URL: 'http://localhost:9200' });
  });

  it('substitutes multiple refs across multiple templates', () => {
    expect(
      resolveDerivedEnv(
        {
          BACKEND_CORS_ORIGINS: 'http://localhost:${FRONTEND_PORT},http://localhost',
          FRONTEND_HOST: 'http://localhost:${FRONTEND_PORT}',
          API: '${HOST}:${BACKEND_PORT}',
        },
        { FRONTEND_PORT: 6373, BACKEND_PORT: 9200, HOST: 5 },
      ),
    ).toEqual({
      BACKEND_CORS_ORIGINS: 'http://localhost:6373,http://localhost',
      FRONTEND_HOST: 'http://localhost:6373',
      API: '5:9200',
    });
  });

  it('leaves an unknown ref literal rather than blanking it', () => {
    expect(resolveDerivedEnv({ X: 'a-${MISSING}-b' }, { OTHER: 1 })).toEqual({
      X: 'a-${MISSING}-b',
    });
  });
});

describe('composeWorktreeEnv', () => {
  it('emits port vars in order, then resolved derived vars', () => {
    expect(
      composeWorktreeEnv(
        [
          ['FRONTEND_PORT', 6373],
          ['BACKEND_PORT', 9200],
        ],
        {
          VITE_API_URL: 'http://localhost:${BACKEND_PORT}',
          BACKEND_CORS_ORIGINS: 'http://localhost:${FRONTEND_PORT}',
        },
      ),
    ).toEqual([
      ['FRONTEND_PORT', '6373'],
      ['BACKEND_PORT', '9200'],
      ['VITE_API_URL', 'http://localhost:9200'],
      ['BACKEND_CORS_ORIGINS', 'http://localhost:6373'],
    ]);
  });

  it('returns just the port vars when there are no derived templates', () => {
    expect(composeWorktreeEnv([['BACKEND_PORT', 9200]])).toEqual([['BACKEND_PORT', '9200']]);
  });
});

describe('formatEnvExport', () => {
  it('renders sourceable export lines with single-quoted values', () => {
    const out = formatEnvExport([
      ['BACKEND_PORT', 9200],
      ['VITE_API_URL', 'http://localhost:9200'],
    ]);
    expect(out).toContain("export BACKEND_PORT='9200'");
    expect(out).toContain("export VITE_API_URL='http://localhost:9200'");
    expect(out.startsWith('# Generated by Dash')).toBe(true);
    expect(out.endsWith('\n')).toBe(true);
  });

  it('escapes single quotes in a value', () => {
    expect(formatEnvExport([['Q', "a'b"]])).toContain(`export Q='a'\\''b'`);
  });
});
